### PR TITLE
Standardize command line argument parsing

### PR DESCRIPTION
**Pull request by ffranr**
I don't consider this work finished. Will need to go through it once more. Looking for early feedback if possible.

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
This adds a new dependency, and also adds more code. I'm really not sure that the old one is that unreadable, and seems to work fine, so why the change? Generally I'm really not a fan of adding new dependencies as it just increses exposure in security-critical code.

**Comment by rffrancon** [comment]
Thank you for your reply.

This PR aims to improve upon/rectify the following program behaviors:
1) The program description and the entire list of parameter descriptions are written to stdout everytime the program runs.
2) Standard flags such as `--version` and `--help` are not supported.

In broad terms, the aim of this PR is to standardize one aspect of the project. A clear and standardized README and command-line interface gives users/developers confidence that they can trust the code.*

These are the points that you've raised as I understand them:
1) PR adds a new dependency (increases attack surface)
2) PR adds more code
3) old code was readable and working, why change?

Points (1) and (2) are accurate. They are both drawbacks which should be weighed against (any) value added.

On point (3): outputting the program description at each run is arguably erroneous behavior. The PR attempts to simplify the current main function by splitting it into three simpler functions: define the CLI interface `clap_parser_config(.)`, parse CLI arguments `parse_command_line_arguments(.)`, and call into other `mining-proxy` routines `main(.)`.

* The book "Producing Open Source Software" by Karl Fogel discusses the importance of project first impressions.

**Comment by TheBlueMatt** [comment]
Hmm, fair, happy to see version and help flags added and skip printing if arg pargin succeeds. Given most users are gonna be tweaking the software to use it anyway I'm not as worried about that as adding new dependencies, though I admit the story there is already pretty bad, though luckily they're mostly pretty standard rust ecosystem crates.

**Comment by rffrancon** [comment]
From my standpoint, this PR is ready for review.

@TheBlueMatt I've been thinking further about the external crate dependency security concern which you raised. From what I understand, a crate of a given version published on `crates.io` can never be overwritten. This guarantee obviously involves trusting `crates.io` and the checksum repo `https://github.com/rust-lang/crates.io-index`.

What are your thoughts on specifying all dependencies using a (release) git commit instead? For example:
```
[dependencies]
clap = { git = "https://github.com/clap-rs/clap.git", rev = "07c15d28d94ffb0ba52b895cd75404c73ed5d10a" }
```
Of course, `clap` internal dependency management probably relies heavily on `crates.io` once more.

If you know of any good texts on security aware dependency management, I would be very grateful to hear of them.

I've attached a graph of `mining-proxy`'s crates dependency graph. It was created using [cargo-graph](https://github.com/kbknapp/cargo-graph). Figure key:
> optional dependencies to use red dashed lines and black boxes, and regular (aka "build") dependencies to use orange lines to green diamonds

mining_proxy_graph

**Pull request closed without merging**
